"""Pure extraction helpers over Claude Code transcript JSONL entries.

All functions in this module are deterministic and side-effect-free so they
can be unit-tested against fixture transcripts without any external state.
"""
from __future__ import annotations

import json
import os
import re
from typing import Iterable

REVERSAL_MARKERS = re.compile(
    r"\b(no|nope|stop|wait|actually|instead|don'?t|never\s?mind|undo|revert|switch|"
    r"change\s+(?:\w+\s+){0,3}(?:plan|approach|direction|strategy|method))\b",
    re.IGNORECASE,
)
DECISION_MARKERS = re.compile(
    r"\b(decid(e|ed)|let's\s+(go|do)|use\s+\w+\s+instead|going\s+with)\b",
    re.IGNORECASE,
)
CODE_FENCE = re.compile(r"```[\s\S]*?```")
ERROR_MARKERS = re.compile(r"\berror\b|\btraceback\b|\bfailed\b|exit\s+code\s+[1-9]", re.IGNORECASE)

PRINTABLE_TOOL_INPUT_KEYS = {
    "Bash": ("command",),
    "Read": ("file_path",),
    "Edit": ("file_path",),
    "Write": ("file_path",),
    "Grep": ("pattern", "path"),
    "Glob": ("pattern", "path"),
    "WebFetch": ("url",),
    "WebSearch": ("query",),
    "TaskCreate": ("subject",),
    "TaskUpdate": ("taskId", "status"),
    # Clarifying question to the user — the question text IS the signal.
    "AskUserQuestion": ("question",),
    # Sub-agent dispatch — show what was researched, not just `[Agent]`.
    "Agent": ("description", "subagent_type"),
    "Task": ("description", "subagent_type"),
    # Skill invocation — without this the marker is bare `[Skill]` (no signal).
    "Skill": ("skill",),
}

# Per-tool max value length. Bash commands are ephemeral and bloat the brief.
# Bash limit was 40 — too tight for `git -C /long/path …` style invocations
# where the first 40 chars were eaten by the path before the actual verb.
TOOL_VALUE_LIMITS = {
    "Bash": 60,
    "WebFetch": 60,
    "WebSearch": 60,
}
DEFAULT_TOOL_VALUE_LIMIT = 100

# Tools whose primary key is a file path. Used to apply basename-only
# rendering on repeat occurrences.
PATH_TOOLS = frozenset({"Read", "Edit", "Write", "Grep", "Glob"})

DROP_TOP_TYPES = frozenset({
    "attachment",
    "file-history-snapshot",
    "ai-title",
    "agent-name",
    "last-prompt",
    "permission-mode",
    "system",
})

# Patterns that mark a user msg as noise (not a real signal-bearing turn).
SHORT_ACK_RE = re.compile(
    r"^\s*(ok|okay|yes|yep|yup|no|nope|nah|sure|thanks|thank\s*you|go|done|"
    r"good|great|perfect|cool|nice|right|correct|fine|alright|k|kk|"
    r"\d{1,3}|[a-z]{1,3})\s*[.!?]?\s*$",
    re.IGNORECASE,
)
COMPACTION_CONTINUATION_RE = re.compile(
    r"^\s*This session is being continued from a previous conversation",
    re.IGNORECASE,
)
SKILL_BODY_MARKERS = (
    "Base directory for this skill:",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)

# Prefixes of CC-system-injected pseudo-user msgs that aren't real intent.
SYSTEM_INJECTED_PREFIXES = (
    "Shell cwd was reset to",
    "Caveat: The messages below were generated by the user",
    "<system-reminder>",
    # Async sub-agent / background-task completion pings — wraps real user
    # blocks but the wrapper itself is system-generated.
    "<task-notification>",
)

# Heuristic: a user msg that's mostly a paste of CLI output. Real intent
# usually leads, then drowns in a wall of `❯ …` / `Ran NN shell commands` /
# `Status:`-style status dumps. Don't drop entirely (keeps signal), but
# elide the long tail so a fresh /handoff doesn't carry forward 50 KB of
# someone else's terminal scroll.
PASTED_OUTPUT_LEAD = re.compile(r"(?m)(?:^❯ |Ran\s+\d+\s+shell commands\b)")
PASTED_OUTPUT_LINE = re.compile(
    r"(?m)^(?:[A-Za-z][\w-]+:\s|-\s|\s*\d+\.\s|❯\s|\s*Ran\s+\d+\s+shell)"
)
PASTED_PRESERVE_CHARS = 200


def is_pasted_terminal_output(text: str) -> bool:
    """True when `text` looks like a paste of CC's terminal output.

    Two-stage signal: a clear lead pattern (a `❯ ` line or a
    `Ran N shell commands`), AND at least 3 status-shaped lines after the
    lead. Bare command output without a lead does not match — we want
    high precision so genuine prose isn't elided.
    """
    if not text:
        return False
    if not PASTED_OUTPUT_LEAD.search(text):
        return False
    return len(PASTED_OUTPUT_LINE.findall(text)) >= 3


def elide_pasted_output(text: str, preserve_chars: int = PASTED_PRESERVE_CHARS) -> str:
    """Return `text` with the pasted-output tail collapsed to a marker.

    Only triggers for inputs `is_pasted_terminal_output` recognizes, and
    only when the elision would actually save bytes. Keeps the first
    `preserve_chars` characters intact so the user's leading intent
    survives.
    """
    if not is_pasted_terminal_output(text):
        return text
    head = text[:preserve_chars].rstrip()
    elided = len(text) - len(head)
    if elided <= 0:
        return text
    return f"{head}\n…[elided {elided // 1000}k of pasted terminal output]"


def load_jsonl(path: str) -> list[dict]:
    out: list[dict] = []
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def is_real_user(entry: dict) -> bool:
    """A `user` entry is a REAL user input only if its content is a plain
    string or a list of text-only blocks. Synthetic wraps holding tool_result
    blocks are CC's internal mechanism for piping tool output back to the
    model and must be dropped.

    `isMeta: True` flags CC-injected pseudo-user msgs (e.g. slash command
    body text from commands/*.md). These look like user text but the user
    never typed them — drop them so they don't pollute the brief."""
    if entry.get("type") != "user":
        return False
    if entry.get("isMeta") is True:
        return False
    msg = entry.get("message", {})
    content = msg.get("content")
    if isinstance(content, str):
        return content.strip() != ""
    if isinstance(content, list):
        has_text = any(isinstance(b, dict) and b.get("type") == "text" for b in content)
        has_tool_result = any(isinstance(b, dict) and b.get("type") == "tool_result" for b in content)
        return has_text and not has_tool_result
    return False


def user_text(entry: dict) -> str:
    msg = entry.get("message", {})
    c = msg.get("content")
    if isinstance(c, str):
        return c.strip()
    if isinstance(c, list):
        parts = [b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text"]
        return "\n".join(p for p in parts if p).strip()
    return ""


def assistant_blocks(entry: dict) -> list[dict]:
    msg = entry.get("message", {})
    c = msg.get("content")
    if isinstance(c, list):
        return [b for b in c if isinstance(b, dict)]
    return []


def _collapse_home(s: str) -> str:
    """Replace `$HOME` prefix with `~` so absolute paths in markers stay
    short. Idempotent. Reads $HOME at call time so tests can mock it."""
    home = os.environ.get("HOME") or ""
    if home and len(home) > 1 and home in s:
        return s.replace(home, "~")
    return s


def short_tool_input(
    name: str,
    inp: dict,
    max_value_len: int | None = None,
    seen_paths: set[str] | None = None,
) -> str:
    """Render a tool_use as a one-line marker like `[Bash command=git status]`.

    `max_value_len` overrides the per-tool limit if given.
    `seen_paths` tracks file paths already shown in this brief — when a
    PATH_TOOLS tool is called on a path already seen, the marker uses just
    the basename to save bytes.

    Special-case AskUserQuestion: its `input` carries
    `{"questions": [{"question": "...", ...}, ...]}`. We surface the first
    question text plus a count so the marker actually carries signal.
    """
    if name == "AskUserQuestion":
        qs = inp.get("questions") if isinstance(inp, dict) else None
        if isinstance(qs, list) and qs:
            first = qs[0] if isinstance(qs[0], dict) else {}
            q = str(first.get("question") or "").replace("\n", " ").strip()
            limit = max_value_len if max_value_len is not None else DEFAULT_TOOL_VALUE_LIMIT
            if len(q) > limit:
                q = q[: limit - 3] + "..."
            tail = f" +{len(qs) - 1} more" if len(qs) > 1 else ""
            return f"[{name} q={q}{tail}]" if q else f"[{name}]"
        return f"[{name}]"

    keys = PRINTABLE_TOOL_INPUT_KEYS.get(name, ())
    limit = max_value_len if max_value_len is not None else TOOL_VALUE_LIMITS.get(name, DEFAULT_TOOL_VALUE_LIMIT)

    parts = []
    for k in keys:
        v = inp.get(k)
        if v is None:
            continue
        s = str(v).replace("\n", " ").strip()
        s = _collapse_home(s)
        if name in PATH_TOOLS and k in ("file_path", "path") and seen_paths is not None:
            if s in seen_paths:
                # Already rendered this path verbatim earlier; collapse to basename
                s = s.rsplit("/", 1)[-1] if "/" in s else s
            else:
                seen_paths.add(s)
        if len(s) > limit:
            s = s[: limit - 3] + "..."
        parts.append(f"{k}={s}")
    return f"[{name}{' ' + ' '.join(parts) if parts else ''}]"


def iter_real_user_msgs(entries: Iterable[dict]) -> list[str]:
    """Every real user msg, including noise. Used for the full-archive doc."""
    out = []
    for e in entries:
        if is_real_user(e):
            t = user_text(e)
            if t:
                out.append(t)
    return out


def is_noise_user_msg(text: str) -> bool:
    """Return True for user msgs that are obvious noise and shouldn't bloat
    the trimmed brief. The full text is still preserved in the memory doc
    archive — this only filters what makes it into the trimmed brief."""
    s = text.strip()
    if not s:
        return True
    if SHORT_ACK_RE.match(s):
        return True
    if COMPACTION_CONTINUATION_RE.match(s):
        return True
    if any(marker in s for marker in SKILL_BODY_MARKERS):
        return True
    if any(s.startswith(p) for p in SYSTEM_INJECTED_PREFIXES):
        return True
    if s.startswith("---\nname:") and "description:" in s[:200]:
        # Slash command frontmatter pasted as user input
        return True
    return False


def iter_signal_user_msgs(entries: Iterable[dict]) -> list[str]:
    """Real user msgs minus noise (short acks, skill bodies, compaction
    continuations) and exact duplicates. Order = first occurrence.

    Pasted terminal-output blocks are kept (the lead carries intent) but
    the long tail is elided so the brief stays compact."""
    seen: dict[str, None] = {}
    for e in entries:
        if not is_real_user(e):
            continue
        t = user_text(e)
        if not t or is_noise_user_msg(t):
            continue
        t = elide_pasted_output(t)
        if t in seen:
            continue
        seen[t] = None
    return list(seen.keys())


def extract_decisions(user_msgs: list[str]) -> list[str]:
    return [m for m in user_msgs if REVERSAL_MARKERS.search(m) or DECISION_MARKERS.search(m)]


# Paths under these prefixes are scratch/system noise — never carry resume
# value. Filtered out of `extract_files_touched` regardless of cwd.
_NOISE_PATH_PREFIXES = (
    "/tmp/",
    "/private/var/folders/",
    "/private/tmp/",
    "/var/folders/",
    "/usr/",
    "/bin/",
    "/sbin/",
    "/Library/",
    "/System/",
)
# These ~-rooted paths are also session/tooling scratch.
_NOISE_HOME_PREFIXES = (
    "~/.claude/compaction/",
    "~/.claude/projects/",
    "~/.claude/tools/",
    "~/.claude/cache/",
)


def _is_noise_path(p: str, cwd: str | None) -> bool:
    """Return True if `p` is a scratch / system path that should be filtered
    from `Files Touched`. Paths under `cwd` (when provided) are always kept;
    everything else is checked against the noise prefix lists."""
    if not p:
        return True
    if cwd:
        # Normalize cwd (strip trailing slash, expand ~).
        c = cwd.rstrip("/")
        if c and (p == c or p.startswith(c + "/")):
            return False
        # Match against ~-relative form too.
        import os as _os

        home = _os.path.expanduser("~")
        if home and c.startswith(home):
            tilde = "~" + c[len(home):]
            if p == tilde or p.startswith(tilde + "/"):
                return False
    if p.startswith(_NOISE_PATH_PREFIXES):
        return True
    if p.startswith(_NOISE_HOME_PREFIXES):
        return True
    return False


def extract_files_touched(
    entries: Iterable[dict], cwd: str | None = None
) -> list[str]:
    """Deduped list of file paths from Read/Edit/Write tool_use + paths
    appearing in Bash commands. Order = first occurrence.

    When `cwd` is supplied, paths under cwd are always kept and paths
    matching the system/scratch noise prefixes (`/tmp/`, `/usr/`, etc.)
    are dropped. When `cwd` is None, only the noise-prefix filter runs —
    callers without cwd context still benefit from filtering the obvious
    scratch dirs."""
    seen: dict[str, None] = {}
    bash_path_re = re.compile(r"(?:^|\s)((?:/|~/|\./)[\w./~+-]{2,})")
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") != "tool_use":
                continue
            name = b.get("name")
            inp = b.get("input", {}) or {}
            if name in ("Read", "Edit", "Write"):
                p = inp.get("file_path")
                if p and not _is_noise_path(str(p), cwd):
                    seen.setdefault(str(p), None)
            elif name == "Grep":
                p = inp.get("path")
                if p and not _is_noise_path(str(p), cwd):
                    seen.setdefault(str(p), None)
            elif name == "Bash":
                cmd = inp.get("command", "") or ""
                for p in bash_path_re.findall(cmd):
                    if not _is_noise_path(p, cwd):
                        seen.setdefault(p, None)
    return list(seen.keys())


SUBAGENT_TOOL_NAMES = frozenset({"Agent", "Task"})
# Below this length, treat as stub ("Task interrupted by user", etc.) and skip.
AGENT_REPORT_MIN_CHARS = 200


def extract_agent_reports(
    entries: Iterable[dict],
    *,
    max_chars: int = 1500,
    min_chars: int = AGENT_REPORT_MIN_CHARS,
) -> list[tuple[str, str, str]]:
    """Pull synthesized sub-agent reports out of the transcript.

    Returns `(description, subagent_type, report_text)` tuples in chronological
    order. Identifies reports by `tool_use_id` linkage between an assistant
    `tool_use` block whose `name` is `Agent`/`Task` and the matching `tool_result`
    in a later synthetic `user` entry.

    These reports are high-signal synthesized text (median ~1.9k chars across
    real fixtures) that today's pipeline drops along with all other tool_results.
    Unlike Bash/Read output, they're NOT recoverable from any other source —
    losing them forces a re-run of the agent next session, wasting tokens and
    obscuring why a decision was made.

    Truncation is per-report at `max_chars` for tier1 budget. Tier2 should
    pass a much larger cap (or 0) to keep full bodies.
    """
    use_idx: dict[str, tuple[str, str]] = {}
    entries = list(entries)
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") != "tool_use":
                continue
            if b.get("name") not in SUBAGENT_TOOL_NAMES:
                continue
            inp = b.get("input") or {}
            use_idx[str(b.get("id") or "")] = (
                str(inp.get("description") or ""),
                str(inp.get("subagent_type") or ""),
            )

    out: list[tuple[str, str, str]] = []
    for e in entries:
        if e.get("type") != "user":
            continue
        c = e.get("message", {}).get("content")
        if not isinstance(c, list):
            continue
        # Prefer the top-level `toolUseResult.content` when present — it holds
        # the clean synthesized text without the inline UI noise (`agentId: ...`,
        # trailing `<usage>` blocks) that lives in the displayed tool_result body.
        tur_text = _agent_report_text_from_tooluseresult(e.get("toolUseResult"))
        for b in c:
            if not (isinstance(b, dict) and b.get("type") == "tool_result"):
                continue
            meta = use_idx.get(str(b.get("tool_use_id") or ""))
            if not meta:
                continue
            text = tur_text
            if not text:
                tc = b.get("content")
                if isinstance(tc, list):
                    text = "\n".join(
                        blk.get("text", "")
                        for blk in tc
                        if isinstance(blk, dict) and blk.get("type") == "text"
                    )
                elif isinstance(tc, str):
                    text = tc
            text = (text or "").strip()
            if len(text) < min_chars:
                continue
            if max_chars and len(text) > max_chars:
                text = text[: max_chars - 3].rstrip() + "..."
            out.append((meta[0], meta[1], text))
    return out


def _agent_report_text_from_tooluseresult(tur: object) -> str:
    """Extract clean text from the top-level `toolUseResult.content` array on a
    user entry. Returns "" when the field is absent or shaped differently."""
    if not isinstance(tur, dict):
        return ""
    content = tur.get("content")
    if not isinstance(content, list):
        return ""
    parts = [
        blk.get("text", "")
        for blk in content
        if isinstance(blk, dict) and blk.get("type") == "text"
    ]
    return "\n".join(p for p in parts if p).strip()


# Patterns that look like errors but carry zero diagnostic value once
# isolated: bare exit codes from RTK / shell wrappers, single-token
# "Error" or "Failed", etc. Filtering these stops the brief from
# advertising "Errors Hit (5)" when none of them actually surface a fault.
_EXIT_CODE_ONLY_RE = re.compile(
    r"^\s*(?:Exit code\s*\d+|Error\s+code\s*\d+|Failed\.?|Error\.?)\s*$",
    re.IGNORECASE,
)
_ERROR_MIN_BODY_CHARS = 20


def _is_diagnostic_error(text: str) -> bool:
    """Reject error snippets that have no stderr / message body. We require
    at least `_ERROR_MIN_BODY_CHARS` of content AND not match the
    exit-code-only pattern. Real diagnostic errors (tracebacks, stderr
    lines, structured "Error: <reason>" prose) survive."""
    s = text.strip()
    if len(s) < _ERROR_MIN_BODY_CHARS:
        return False
    if _EXIT_CODE_ONLY_RE.match(s):
        return False
    return True


def extract_errors(entries: Iterable[dict], limit: int = 5, snippet_len: int = 300) -> list[str]:
    """Last N error-like tool_result snippets with a real diagnostic body.

    Bodies under `_ERROR_MIN_BODY_CHARS` (default 20) and pure exit-code
    patterns are dropped — they carry no resume value and clutter tier1
    with "Errors Hit (5)" headers that contain only `Exit code 1`."""
    errs: list[str] = []
    for e in entries:
        if e.get("type") != "user":
            continue
        msg = e.get("message", {})
        c = msg.get("content")
        if not isinstance(c, list):
            continue
        for b in c:
            if not isinstance(b, dict) or b.get("type") != "tool_result":
                continue
            tc = b.get("content")
            text = ""
            if isinstance(tc, list):
                text = " ".join(
                    blk.get("text", "")
                    for blk in tc
                    if isinstance(blk, dict) and blk.get("type") == "text"
                )
            elif isinstance(tc, str):
                text = tc
            if not text:
                continue
            if not (ERROR_MARKERS.search(text) or b.get("is_error")):
                continue
            if not _is_diagnostic_error(text):
                continue
            errs.append(text.strip()[:snippet_len])
    return errs[-limit:]


def extract_code_anchors(entries: Iterable[dict], min_lines: int = 5) -> list[str]:
    out: list[str] = []
    for e in entries:
        if e.get("type") not in ("user", "assistant"):
            continue
        msg = e.get("message", {})
        c = msg.get("content")
        texts: list[str] = []
        if isinstance(c, str):
            texts.append(c)
        elif isinstance(c, list):
            for b in c:
                if isinstance(b, dict) and b.get("type") == "text":
                    texts.append(b.get("text", ""))
        for t in texts:
            for fence in CODE_FENCE.findall(t):
                if fence.count("\n") >= min_lines:
                    out.append(fence)
    return out


# Stopwords that drag down keyword-overlap signal: pure-grammar words +
# meta words like "code"/"file" that appear in nearly every code anchor.
_STOPWORDS = frozenset(
    {
        "a", "an", "and", "are", "as", "at", "be", "by", "do", "for",
        "from", "has", "have", "i", "if", "in", "is", "it", "its", "me",
        "my", "no", "not", "of", "on", "or", "so", "that", "the", "this",
        "to", "we", "with", "you", "your", "all", "any", "but", "can",
        "will", "would", "should", "could", "want", "need", "let", "lets",
        "code", "file", "some", "more", "less", "than", "then", "when",
        "where", "what", "which", "how", "why", "use", "using", "used",
        "fix", "make", "see", "show", "run", "do",
    }
)
_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_]{2,}")


def _tokenize_for_relevance(text: str) -> set[str]:
    """Lowercase tokens of length >=3, stopwords removed. Used for the
    bag-of-words goal/anchor overlap score."""
    return {
        t.lower() for t in _TOKEN_RE.findall(text or "") if t.lower() not in _STOPWORDS
    }


def rerank_code_anchors_by_goal(
    anchors: list[str], goal: str, *, drop_bottom_half: bool = True
) -> list[str]:
    """Sort code anchors by token-overlap with `goal`, descending.

    When `drop_bottom_half` is True (the brief default), anchors whose
    overlap score is in the lower half of the distribution are dropped —
    they're cluttering the brief without contributing to the active task.
    Anchors with score 0 are always dropped when `goal` is non-empty.

    No-op (returns input) if `goal` is empty or fewer than 2 anchors.
    Stable for ties: preserves original order among equal-score items."""
    if not goal or len(anchors) < 2:
        return list(anchors)
    goal_tokens = _tokenize_for_relevance(goal)
    if not goal_tokens:
        return list(anchors)
    scored: list[tuple[int, int, str]] = []
    for i, a in enumerate(anchors):
        score = len(_tokenize_for_relevance(a) & goal_tokens)
        scored.append((score, i, a))
    scored.sort(key=lambda x: (-x[0], x[1]))
    # Drop zero-score anchors first.
    nonzero = [item for item in scored if item[0] > 0]
    if not nonzero:
        # Goal didn't overlap with any anchor — keep originals in order.
        return list(anchors)
    if drop_bottom_half and len(nonzero) > 1:
        # Median-cut: keep the top ceil(N/2).
        keep = (len(nonzero) + 1) // 2
        nonzero = nonzero[:keep]
    return [a for _, _, a in nonzero]


def extract_todo_snapshot(entries: Iterable[dict]) -> str | None:
    """Most recent TaskCreate/TaskUpdate input as JSON string, or None."""
    last: dict | None = None
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") == "tool_use" and b.get("name") in ("TaskCreate", "TaskUpdate"):
                last = b.get("input")
    return json.dumps(last, indent=2) if last else None


# Phrases that signal the assistant is asking the user for direction. We
# match these in addition to plain `?` to capture explicit handoff cues
# even when the question mark lands on a continuation line.
_OPEN_QUESTION_PHRASE_RE = re.compile(
    r"\b(?:next step|want me to|shall i|should i|ok to|go ahead\?|"
    r"continue\?|proceed\?)\b",
    re.IGNORECASE,
)
# A markdown table is at minimum a header row + a separator like `| --- |`
# + at least one body row. We require all three so we don't latch onto
# stray pipe-bearing prose ("she said `|` is unsafe"). Use `[ \t]*` (NOT
# `\s*`) so blank-line boundaries between back-to-back tables aren't
# silently absorbed into the same match.
_TABLE_BLOCK_RE = re.compile(
    r"(?:^|\n)("
    r"(?:\|[^\n]+\|[ \t]*\n)+"   # 1+ header rows (typically 1)
    r"\|[\s\-:|]+\|[ \t]*\n"      # separator row: | --- | --- |
    r"(?:\|[^\n]+\|[ \t]*\n?)+"   # 1+ body rows
    r")",
    re.MULTILINE,
)
# Decision verbs in assistant text — the verbs the user's review flagged
# in handoff-recommendations.md as load-bearing for "what changed". We
# allow up to ~40 chars of line preamble (e.g. "I'll be ", "Just ") so
# the verb doesn't need to be at the absolute line start.
_DECISION_VERB_RE = re.compile(
    r"^.{0,40}?\b(?:Adding|Removing|Removed|Renaming|Renamed|"
    r"Switching|Switched|Dropping|Dropped|Force-?removed|Force-?removing|"
    r"Replaced|Replacing|Bumping|Bumped|Reverted|Reverting|Migrating|"
    r"Migrated|Wired|Wiring|Pinned|Pinning|Disabled|Disabling|Enabled|"
    r"Enabling|Skipped|Skipping)\b",
    re.IGNORECASE | re.MULTILINE,
)


def _last_assistant_texts(entries: list[dict], n: int) -> list[str]:
    """Return up to `n` most-recent assistant text turns, oldest first."""
    out: list[str] = []
    for e in reversed(entries):
        if e.get("type") != "assistant":
            continue
        text = ""
        for b in assistant_blocks(e):
            if isinstance(b, dict) and b.get("type") == "text":
                text += (b.get("text") or "")
        text = text.strip()
        if text:
            out.append(text)
            if len(out) >= n:
                break
    return list(reversed(out))


def extract_compact_summaries(entries: Iterable[dict]) -> list[str]:
    """Return each Claude Code default `/compact` summary text in order.

    These are user-typed entries flagged with `isCompactSummary: true`,
    written by CC's LLM summarizer when the session was compacted. Used
    by the report's tier1-vs-CC comparison panel — comparing our
    deterministic brief against the lossy paraphrased baseline that
    motivated this whole project."""
    out: list[str] = []
    for e in entries:
        if not e.get("isCompactSummary"):
            continue
        msg = e.get("message", {})
        c = msg.get("content")
        text = ""
        if isinstance(c, str):
            text = c
        elif isinstance(c, list):
            for b in c:
                if isinstance(b, dict) and b.get("type") == "text":
                    text = b.get("text", "")
                    break
        text = (text or "").strip()
        if text:
            out.append(text)
    return out


def extract_open_question(entries: Iterable[dict]) -> str | None:
    """Find the last unresolved question in the assistant transcript.

    Strategy: walk assistant text turns from newest to oldest. Return the
    last sentence that ends in `?` OR contains an open-question phrase
    (`next step`, `want me to`, `shall I`, etc.). Caps at 280 chars so
    multi-sentence questions don't blow the brief budget.

    Returns None when nothing matches — callers should omit the section
    entirely rather than print an empty stub."""
    entries = list(entries)
    for e in reversed(entries):
        if e.get("type") != "assistant":
            continue
        text = ""
        for b in assistant_blocks(e):
            if isinstance(b, dict) and b.get("type") == "text":
                text += (b.get("text") or "")
        if not text.strip():
            continue
        # Search sentence-by-sentence from the end for `?` or phrase match.
        sentences = re.split(r"(?<=[.!?])\s+", text.strip())
        for sent in reversed(sentences):
            s = sent.strip()
            if not s:
                continue
            if s.endswith("?") or _OPEN_QUESTION_PHRASE_RE.search(s):
                return s[:280]
    return None


# Patterns for `synthesize_active_goal`: numeric outcomes (X → Y) and
# action verbs that imply state changes worth surfacing in the goal.
_GOAL_NUMBER_RE = re.compile(
    r"\b\d+\s*(?:→|->|to)\s*\d+\b",
)
_GOAL_VERB_NUMBER_RE = re.compile(
    r"\b(?:dropped|removed|deleted|created|added|"
    r"reduced|cut|trimmed|shrunk|kept|ran|tested|fixed)"
    r"\s+\d+\b",
    re.IGNORECASE,
)


def synthesize_active_goal(
    entries: Iterable[dict],
    fallback: str | None,
    *,
    last_assistant_turns: int = 3,
    max_chars: int = 280,
) -> str | None:
    """Compose a state line from the last few assistant turns.

    Strategy:
    1. Walk last `last_assistant_turns` assistant text turns.
    2. Find sentences containing numeric outcomes (`277 → 26`,
       `dropped 252`, `reduced 100 to 30`) — those are state markers.
    3. Find an open-question sentence in the same window (re-uses the
       open-question matcher).
    4. Compose: `<state>; <pending>` if both present, else whichever.
    5. Fall back to `fallback` (typically last signal user msg) when
       neither state nor pending are extractable.

    Returns None when there's nothing to surface AND no fallback. Caps
    output at `max_chars` to keep tier1 budget intact."""
    entries = list(entries)
    last_texts = _last_assistant_texts(entries, last_assistant_turns)

    state_sentences: list[str] = []
    for text in last_texts:
        for sent in re.split(r"(?<=[.!?])\s+", text):
            s = sent.strip()
            if not s:
                continue
            if _GOAL_NUMBER_RE.search(s) or _GOAL_VERB_NUMBER_RE.search(s):
                state_sentences.append(s)

    # Use the most-recent state sentence (last in chronological order).
    state = state_sentences[-1] if state_sentences else ""
    pending = extract_open_question(entries) or ""

    parts: list[str] = []
    if state:
        parts.append(state)
    if pending and pending not in state:
        parts.append(pending)
    if not parts:
        return fallback
    composed = " ".join(parts)
    if len(composed) > max_chars:
        composed = composed[: max_chars - 3].rstrip() + "..."
    return composed


def extract_decisions_made(entries: Iterable[dict], limit: int = 10) -> list[str]:
    """Return up to `limit` decision-statement bullets in chronological order.

    Sources:
      * Assistant text lines starting with a decision verb (Removing,
        Force-removed, Pinned, Reverted, etc.) — the prose log of what
        was done in this session.
      * `git commit -m <msg>` first lines pulled out of Bash tool_use
        commands — committed work IS a decision record.

    Lines are deduped (case-insensitive) and capped to 200 chars each."""
    out: list[str] = []
    seen: set[str] = set()

    def _push(line: str) -> None:
        s = line.strip()
        if not s:
            return
        s = s[:200]
        key = s.lower()
        if key in seen:
            return
        seen.add(key)
        out.append(s)

    git_commit_re = re.compile(
        r"git\s+commit\s+(?:[^\n]*\s)?-m\s+(?:'([^']+)'|\"([^\"]+)\")",
        re.IGNORECASE,
    )

    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if not isinstance(b, dict):
                continue
            bt = b.get("type")
            if bt == "text":
                text = b.get("text") or ""
                for line in text.splitlines():
                    if _DECISION_VERB_RE.match(line):
                        _push(line)
                        if len(out) >= limit:
                            return out
            elif bt == "tool_use" and b.get("name") == "Bash":
                cmd = (b.get("input") or {}).get("command", "") or ""
                for m in git_commit_re.finditer(cmd):
                    msg = m.group(1) or m.group(2) or ""
                    # Take only the subject line of the commit message.
                    subj = msg.splitlines()[0] if msg else ""
                    if subj:
                        _push(f"committed: {subj}")
                        if len(out) >= limit:
                            return out
    return out


def extract_result_tables(
    entries: Iterable[dict], from_last: int = 3, max_tables: int = 0
) -> list[str]:
    """Pull markdown tables from the last `from_last` assistant text turns.

    These are the highest-signal artifacts (drop tallies, disposition
    summaries, sweep results) and rendering them verbatim costs nothing
    — they're already markdown.

    `max_tables=0` returns all matches; pass a positive int to cap (the
    tier1 caller passes 2)."""
    entries = list(entries)
    out: list[str] = []
    seen: set[str] = set()
    for text in _last_assistant_texts(entries, from_last):
        for m in _TABLE_BLOCK_RE.finditer(text):
            tbl = m.group(1).strip()
            if not tbl:
                continue
            key = tbl.lower()
            if key in seen:
                continue
            seen.add(key)
            out.append(tbl)
            if max_tables and len(out) >= max_tables:
                return out
    return out


_PLAN_PATH_RE = re.compile(r"(?:^|/)plans?/.+\.md$", re.IGNORECASE)


def extract_plans_saved(entries: Iterable[dict]) -> list[str]:
    """Return paths of plan files the assistant wrote, in first-write order.

    Detects Write tool_use calls whose `file_path` lives under a `/plans/`
    (or `/plan/`) directory and ends in `.md`. Only the path is captured —
    the file persists on disk, so the brief just needs a pointer. If the
    same plan is written multiple times, only the first occurrence is kept.
    """
    seen: dict[str, None] = {}
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if not (isinstance(b, dict) and b.get("type") == "tool_use"):
                continue
            if b.get("name") != "Write":
                continue
            inp = b.get("input") or {}
            path = str(inp.get("file_path") or "")
            if not path or not _PLAN_PATH_RE.search(path):
                continue
            if path not in seen:
                seen[path] = None
    return list(seen.keys())
