"""Pure extraction helpers over Claude Code transcript JSONL entries.

All functions in this module are deterministic and side-effect-free so they
can be unit-tested against fixture transcripts without any external state.
"""
from __future__ import annotations

import json
import os
import re
from typing import Iterable

REVERSAL_MARKERS = re.compile(
    r"\b(no|nope|stop|wait|actually|instead|don'?t|never\s?mind|undo|revert|switch|"
    r"change\s+(?:\w+\s+){0,3}(?:plan|approach|direction|strategy|method))\b",
    re.IGNORECASE,
)
DECISION_MARKERS = re.compile(
    r"\b(decid(e|ed)|let's\s+(go|do)|use\s+\w+\s+instead|going\s+with)\b",
    re.IGNORECASE,
)
CODE_FENCE = re.compile(r"```[\s\S]*?```")
ERROR_MARKERS = re.compile(r"\berror\b|\btraceback\b|\bfailed\b|exit\s+code\s+[1-9]", re.IGNORECASE)

PRINTABLE_TOOL_INPUT_KEYS = {
    "Bash": ("command",),
    "Read": ("file_path",),
    "Edit": ("file_path",),
    "Write": ("file_path",),
    "Grep": ("pattern", "path"),
    "Glob": ("pattern", "path"),
    "WebFetch": ("url",),
    "WebSearch": ("query",),
    "TaskCreate": ("subject",),
    "TaskUpdate": ("taskId", "status"),
    # Clarifying question to the user — the question text IS the signal.
    "AskUserQuestion": ("question",),
    # Sub-agent dispatch — show what was researched, not just `[Agent]`.
    "Agent": ("description", "subagent_type"),
    "Task": ("description", "subagent_type"),
    # Skill invocation — without this the marker is bare `[Skill]` (no signal).
    "Skill": ("skill",),
}

# Per-tool max value length. Bash commands are ephemeral and bloat the brief.
# Bash limit was 40 — too tight for `git -C /long/path …` style invocations
# where the first 40 chars were eaten by the path before the actual verb.
TOOL_VALUE_LIMITS = {
    "Bash": 60,
    "WebFetch": 60,
    "WebSearch": 60,
}
DEFAULT_TOOL_VALUE_LIMIT = 100

# Tools whose primary key is a file path. Used to apply basename-only
# rendering on repeat occurrences.
PATH_TOOLS = frozenset({"Read", "Edit", "Write", "Grep", "Glob"})

DROP_TOP_TYPES = frozenset({
    "attachment",
    "file-history-snapshot",
    "ai-title",
    "agent-name",
    "last-prompt",
    "permission-mode",
    "system",
})

# Patterns that mark a user msg as noise (not a real signal-bearing turn).
SHORT_ACK_RE = re.compile(
    r"^\s*(ok|okay|yes|yep|yup|no|nope|nah|sure|thanks|thank\s*you|go|done|"
    r"good|great|perfect|cool|nice|right|correct|fine|alright|k|kk|"
    r"\d{1,3}|[a-z]{1,3})\s*[.!?]?\s*$",
    re.IGNORECASE,
)
COMPACTION_CONTINUATION_RE = re.compile(
    r"^\s*This session is being continued from a previous conversation",
    re.IGNORECASE,
)
SKILL_BODY_MARKERS = (
    "Base directory for this skill:",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)

# Prefixes of CC-system-injected pseudo-user msgs that aren't real intent.
SYSTEM_INJECTED_PREFIXES = (
    "Shell cwd was reset to",
    "Caveat: The messages below were generated by the user",
    "<system-reminder>",
    # Async sub-agent / background-task completion pings — wraps real user
    # blocks but the wrapper itself is system-generated.
    "<task-notification>",
)

# Heuristic: a user msg that's mostly a paste of CLI output. Real intent
# usually leads, then drowns in a wall of `❯ …` / `Ran NN shell commands` /
# `Status:`-style status dumps. Don't drop entirely (keeps signal), but
# elide the long tail so a fresh /handoff doesn't carry forward 50 KB of
# someone else's terminal scroll.
PASTED_OUTPUT_LEAD = re.compile(r"(?m)(?:^❯ |Ran\s+\d+\s+shell commands\b)")
PASTED_OUTPUT_LINE = re.compile(
    r"(?m)^(?:[A-Za-z][\w-]+:\s|-\s|\s*\d+\.\s|❯\s|\s*Ran\s+\d+\s+shell)"
)
PASTED_PRESERVE_CHARS = 200


def is_pasted_terminal_output(text: str) -> bool:
    """True when `text` looks like a paste of CC's terminal output.

    Two-stage signal: a clear lead pattern (a `❯ ` line or a
    `Ran N shell commands`), AND at least 3 status-shaped lines after the
    lead. Bare command output without a lead does not match — we want
    high precision so genuine prose isn't elided.
    """
    if not text:
        return False
    if not PASTED_OUTPUT_LEAD.search(text):
        return False
    return len(PASTED_OUTPUT_LINE.findall(text)) >= 3


def elide_pasted_output(text: str, preserve_chars: int = PASTED_PRESERVE_CHARS) -> str:
    """Return `text` with the pasted-output tail collapsed to a marker.

    Only triggers for inputs `is_pasted_terminal_output` recognizes, and
    only when the elision would actually save bytes. Keeps the first
    `preserve_chars` characters intact so the user's leading intent
    survives.
    """
    if not is_pasted_terminal_output(text):
        return text
    head = text[:preserve_chars].rstrip()
    elided = len(text) - len(head)
    if elided <= 0:
        return text
    return f"{head}\n…[elided {elided // 1000}k of pasted terminal output]"


def load_jsonl(path: str) -> list[dict]:
    out: list[dict] = []
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def is_real_user(entry: dict) -> bool:
    """A `user` entry is a REAL user input only if its content is a plain
    string or a list of text-only blocks. Synthetic wraps holding tool_result
    blocks are CC's internal mechanism for piping tool output back to the
    model and must be dropped.

    `isMeta: True` flags CC-injected pseudo-user msgs (e.g. slash command
    body text from commands/*.md). These look like user text but the user
    never typed them — drop them so they don't pollute the brief."""
    if entry.get("type") != "user":
        return False
    if entry.get("isMeta") is True:
        return False
    msg = entry.get("message", {})
    content = msg.get("content")
    if isinstance(content, str):
        return content.strip() != ""
    if isinstance(content, list):
        has_text = any(isinstance(b, dict) and b.get("type") == "text" for b in content)
        has_tool_result = any(isinstance(b, dict) and b.get("type") == "tool_result" for b in content)
        return has_text and not has_tool_result
    return False


def user_text(entry: dict) -> str:
    msg = entry.get("message", {})
    c = msg.get("content")
    if isinstance(c, str):
        return c.strip()
    if isinstance(c, list):
        parts = [b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text"]
        return "\n".join(p for p in parts if p).strip()
    return ""


def assistant_blocks(entry: dict) -> list[dict]:
    msg = entry.get("message", {})
    c = msg.get("content")
    if isinstance(c, list):
        return [b for b in c if isinstance(b, dict)]
    return []


def _collapse_home(s: str) -> str:
    """Replace `$HOME` prefix with `~` so absolute paths in markers stay
    short. Idempotent. Reads $HOME at call time so tests can mock it."""
    home = os.environ.get("HOME") or ""
    if home and len(home) > 1 and home in s:
        return s.replace(home, "~")
    return s


def short_tool_input(
    name: str,
    inp: dict,
    max_value_len: int | None = None,
    seen_paths: set[str] | None = None,
) -> str:
    """Render a tool_use as a one-line marker like `[Bash command=git status]`.

    `max_value_len` overrides the per-tool limit if given.
    `seen_paths` tracks file paths already shown in this brief — when a
    PATH_TOOLS tool is called on a path already seen, the marker uses just
    the basename to save bytes.

    Special-case AskUserQuestion: its `input` carries
    `{"questions": [{"question": "...", ...}, ...]}`. We surface the first
    question text plus a count so the marker actually carries signal.
    """
    if name == "AskUserQuestion":
        qs = inp.get("questions") if isinstance(inp, dict) else None
        if isinstance(qs, list) and qs:
            first = qs[0] if isinstance(qs[0], dict) else {}
            q = str(first.get("question") or "").replace("\n", " ").strip()
            limit = max_value_len if max_value_len is not None else DEFAULT_TOOL_VALUE_LIMIT
            if len(q) > limit:
                q = q[: limit - 3] + "..."
            tail = f" +{len(qs) - 1} more" if len(qs) > 1 else ""
            return f"[{name} q={q}{tail}]" if q else f"[{name}]"
        return f"[{name}]"

    keys = PRINTABLE_TOOL_INPUT_KEYS.get(name, ())
    limit = max_value_len if max_value_len is not None else TOOL_VALUE_LIMITS.get(name, DEFAULT_TOOL_VALUE_LIMIT)

    parts = []
    for k in keys:
        v = inp.get(k)
        if v is None:
            continue
        s = str(v).replace("\n", " ").strip()
        s = _collapse_home(s)
        if name in PATH_TOOLS and k in ("file_path", "path") and seen_paths is not None:
            if s in seen_paths:
                # Already rendered this path verbatim earlier; collapse to basename
                s = s.rsplit("/", 1)[-1] if "/" in s else s
            else:
                seen_paths.add(s)
        if len(s) > limit:
            s = s[: limit - 3] + "..."
        parts.append(f"{k}={s}")
    return f"[{name}{' ' + ' '.join(parts) if parts else ''}]"


def iter_real_user_msgs(entries: Iterable[dict]) -> list[str]:
    """Every real user msg, including noise. Used for the full-archive doc."""
    out = []
    for e in entries:
        if is_real_user(e):
            t = user_text(e)
            if t:
                out.append(t)
    return out


def is_noise_user_msg(text: str) -> bool:
    """Return True for user msgs that are obvious noise and shouldn't bloat
    the trimmed brief. The full text is still preserved in the memory doc
    archive — this only filters what makes it into the trimmed brief."""
    s = text.strip()
    if not s:
        return True
    if SHORT_ACK_RE.match(s):
        return True
    if COMPACTION_CONTINUATION_RE.match(s):
        return True
    if any(marker in s for marker in SKILL_BODY_MARKERS):
        return True
    if any(s.startswith(p) for p in SYSTEM_INJECTED_PREFIXES):
        return True
    if s.startswith("---\nname:") and "description:" in s[:200]:
        # Slash command frontmatter pasted as user input
        return True
    return False


def iter_signal_user_msgs(entries: Iterable[dict]) -> list[str]:
    """Real user msgs minus noise (short acks, skill bodies, compaction
    continuations) and exact duplicates. Order = first occurrence.

    Pasted terminal-output blocks are kept (the lead carries intent) but
    the long tail is elided so the brief stays compact."""
    seen: dict[str, None] = {}
    for e in entries:
        if not is_real_user(e):
            continue
        t = user_text(e)
        if not t or is_noise_user_msg(t):
            continue
        t = elide_pasted_output(t)
        if t in seen:
            continue
        seen[t] = None
    return list(seen.keys())


def extract_decisions(user_msgs: list[str]) -> list[str]:
    return [m for m in user_msgs if REVERSAL_MARKERS.search(m) or DECISION_MARKERS.search(m)]


def extract_files_touched(entries: Iterable[dict]) -> list[str]:
    """Deduped list of file paths from Read/Edit/Write tool_use + paths
    appearing in Bash commands. Order = first occurrence."""
    seen: dict[str, None] = {}
    bash_path_re = re.compile(r"(?:^|\s)((?:/|~/|\./)[\w./~+-]{2,})")
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") != "tool_use":
                continue
            name = b.get("name")
            inp = b.get("input", {}) or {}
            if name in ("Read", "Edit", "Write"):
                p = inp.get("file_path")
                if p:
                    seen.setdefault(str(p), None)
            elif name == "Grep":
                p = inp.get("path")
                if p:
                    seen.setdefault(str(p), None)
            elif name == "Bash":
                cmd = inp.get("command", "") or ""
                for p in bash_path_re.findall(cmd):
                    seen.setdefault(p, None)
    return list(seen.keys())


SUBAGENT_TOOL_NAMES = frozenset({"Agent", "Task"})
# Below this length, treat as stub ("Task interrupted by user", etc.) and skip.
AGENT_REPORT_MIN_CHARS = 200


def extract_agent_reports(
    entries: Iterable[dict],
    *,
    max_chars: int = 1500,
    min_chars: int = AGENT_REPORT_MIN_CHARS,
) -> list[tuple[str, str, str]]:
    """Pull synthesized sub-agent reports out of the transcript.

    Returns `(description, subagent_type, report_text)` tuples in chronological
    order. Identifies reports by `tool_use_id` linkage between an assistant
    `tool_use` block whose `name` is `Agent`/`Task` and the matching `tool_result`
    in a later synthetic `user` entry.

    These reports are high-signal synthesized text (median ~1.9k chars across
    real fixtures) that today's pipeline drops along with all other tool_results.
    Unlike Bash/Read output, they're NOT recoverable from any other source —
    losing them forces a re-run of the agent next session, wasting tokens and
    obscuring why a decision was made.

    Truncation is per-report at `max_chars` for tier1 budget. Tier2 should
    pass a much larger cap (or 0) to keep full bodies.
    """
    use_idx: dict[str, tuple[str, str]] = {}
    entries = list(entries)
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") != "tool_use":
                continue
            if b.get("name") not in SUBAGENT_TOOL_NAMES:
                continue
            inp = b.get("input") or {}
            use_idx[str(b.get("id") or "")] = (
                str(inp.get("description") or ""),
                str(inp.get("subagent_type") or ""),
            )

    out: list[tuple[str, str, str]] = []
    for e in entries:
        if e.get("type") != "user":
            continue
        c = e.get("message", {}).get("content")
        if not isinstance(c, list):
            continue
        # Prefer the top-level `toolUseResult.content` when present — it holds
        # the clean synthesized text without the inline UI noise (`agentId: ...`,
        # trailing `<usage>` blocks) that lives in the displayed tool_result body.
        tur_text = _agent_report_text_from_tooluseresult(e.get("toolUseResult"))
        for b in c:
            if not (isinstance(b, dict) and b.get("type") == "tool_result"):
                continue
            meta = use_idx.get(str(b.get("tool_use_id") or ""))
            if not meta:
                continue
            text = tur_text
            if not text:
                tc = b.get("content")
                if isinstance(tc, list):
                    text = "\n".join(
                        blk.get("text", "")
                        for blk in tc
                        if isinstance(blk, dict) and blk.get("type") == "text"
                    )
                elif isinstance(tc, str):
                    text = tc
            text = (text or "").strip()
            if len(text) < min_chars:
                continue
            if max_chars and len(text) > max_chars:
                text = text[: max_chars - 3].rstrip() + "..."
            out.append((meta[0], meta[1], text))
    return out


def _agent_report_text_from_tooluseresult(tur: object) -> str:
    """Extract clean text from the top-level `toolUseResult.content` array on a
    user entry. Returns "" when the field is absent or shaped differently."""
    if not isinstance(tur, dict):
        return ""
    content = tur.get("content")
    if not isinstance(content, list):
        return ""
    parts = [
        blk.get("text", "")
        for blk in content
        if isinstance(blk, dict) and blk.get("type") == "text"
    ]
    return "\n".join(p for p in parts if p).strip()


def extract_errors(entries: Iterable[dict], limit: int = 5, snippet_len: int = 300) -> list[str]:
    """Last N error-like tool_result snippets."""
    errs: list[str] = []
    for e in entries:
        if e.get("type") != "user":
            continue
        msg = e.get("message", {})
        c = msg.get("content")
        if not isinstance(c, list):
            continue
        for b in c:
            if not isinstance(b, dict) or b.get("type") != "tool_result":
                continue
            tc = b.get("content")
            text = ""
            if isinstance(tc, list):
                text = " ".join(
                    blk.get("text", "")
                    for blk in tc
                    if isinstance(blk, dict) and blk.get("type") == "text"
                )
            elif isinstance(tc, str):
                text = tc
            if not text:
                continue
            if ERROR_MARKERS.search(text) or b.get("is_error"):
                errs.append(text.strip()[:snippet_len])
    return errs[-limit:]


def extract_code_anchors(entries: Iterable[dict], min_lines: int = 5) -> list[str]:
    out: list[str] = []
    for e in entries:
        if e.get("type") not in ("user", "assistant"):
            continue
        msg = e.get("message", {})
        c = msg.get("content")
        texts: list[str] = []
        if isinstance(c, str):
            texts.append(c)
        elif isinstance(c, list):
            for b in c:
                if isinstance(b, dict) and b.get("type") == "text":
                    texts.append(b.get("text", ""))
        for t in texts:
            for fence in CODE_FENCE.findall(t):
                if fence.count("\n") >= min_lines:
                    out.append(fence)
    return out


def extract_todo_snapshot(entries: Iterable[dict]) -> str | None:
    """Most recent TaskCreate/TaskUpdate input as JSON string, or None."""
    last: dict | None = None
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if b.get("type") == "tool_use" and b.get("name") in ("TaskCreate", "TaskUpdate"):
                last = b.get("input")
    return json.dumps(last, indent=2) if last else None


_PLAN_PATH_RE = re.compile(r"(?:^|/)plans?/.+\.md$", re.IGNORECASE)


def extract_plans_saved(entries: Iterable[dict]) -> list[str]:
    """Return paths of plan files the assistant wrote, in first-write order.

    Detects Write tool_use calls whose `file_path` lives under a `/plans/`
    (or `/plan/`) directory and ends in `.md`. Only the path is captured —
    the file persists on disk, so the brief just needs a pointer. If the
    same plan is written multiple times, only the first occurrence is kept.
    """
    seen: dict[str, None] = {}
    for e in entries:
        if e.get("type") != "assistant":
            continue
        for b in assistant_blocks(e):
            if not (isinstance(b, dict) and b.get("type") == "tool_use"):
                continue
            if b.get("name") != "Write":
                continue
            inp = b.get("input") or {}
            path = str(inp.get("file_path") or "")
            if not path or not _PLAN_PATH_RE.search(path):
                continue
            if path not in seen:
                seen[path] = None
    return list(seen.keys())
